export const Perms = Object.freeze({
  VIEW_ALL: "VIEW_ALL",
  VIEW_OWN_CONG: "VIEW_OWN_CONG",
  CREATE: "CREATE",
  EDIT: "EDIT",
  APPROVE: "APPROVE",
  DELETE: "DELETE",
  MANAGE_USERS: "MANAGE_USERS",

  ADOLESCENTES_VIEW: "ADOLESCENTES_VIEW",
  ADOLESCENTES_EDIT: "ADOLESCENTES_EDIT",
  ADOLESCENTES_APPROVE: "ADOLESCENTES_APPROVE",

  CAMISAS_VIEW: "CAMISAS_VIEW",
  CAMISAS_MANAGE: "CAMISAS_MANAGE",
  CAMISAS_FINANCE_MANAGE: "CAMISAS_FINANCE_MANAGE",
  CAMISAS_COMPROVANTES_MANAGE: "CAMISAS_COMPROVANTES_MANAGE",
});